/*
 * Receipt Processor
 *
 * A simple receipt processor
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Receipt struct {
	// The name of the retailer or store the receipt is from.
	Retailer string `json:"retailer" validate:"required,retailer"`

	// The date of the purchase printed on the receipt (YYYY-MM-DD).
	PurchaseDate string `json:"purchaseDate" validate:"required,datetime=2006-01-02"`

	// The time of the purchase printed on the receipt (HH:MM in 24-hour format).
	PurchaseTime string `json:"purchaseTime" validate:"required,datetime=15:04"`

	// Items purchased (must have at least one item).
	Items []Item `json:"items" validate:"required,min=1,dive"`

	// The total amount paid on the receipt (e.g., 6.49).
	Total string `json:"total" validate:"required,total"`
}
