/*
 * Receipt Processor
 *
 * A simple receipt processor
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Item struct {

	// The short description of the product.
	ShortDescription string `json:"shortDescription" validate:"required"`

	// The price of the item (e.g., 6.49).
	Price string `json:"price" validate:"required,price"`
}
